/* NPM Installation Dependencies */
const express = require("express");
const path = require("path");
const swaggerJSdoc = require('swagger-jsdoc');
const swaggerUI = require('swagger-ui-express');

/* Configure Swagger Documentation */
const options = {
  swaggerDefinition: {
    info: {
      title: 'CUBAL Media API',
      version: '1.0.0',
      description: 'Test Express API with autogenerated Swagger Documentation.'
    },
  },
  // List of files to be processes which use Swagger Documentation methods.
  apis: [
    path.resolve(__dirname, 'router.js'),
    path.resolve(__dirname, 'userRouter.js'),
    path.resolve(__dirname, 'organizationRouter.js'),
    path.resolve(__dirname, 'eventRouter.js')],
};

const specs = swaggerJSdoc(options);

/* Utility Functions */
const {
  wipeAndAdd
} = require("../util/dataManipulation");

const router = express.Router();

/********** API DOCUMENTATION **********/

router.use('/api-docs', swaggerUI.serve, swaggerUI.setup(specs));

/********** DUMMY DATA FUNCTIONALITY /**********/

/* Wipe current DB. */
router.get("/wipe-and-add/:num", wipeAndAdd);

module.exports = router;
